name: workflow-creator-decompose
description: Decompose complex requirements into sub-workflows and generate them recursively
version: "1.0"
tags: [agents, recursive, internal, meta]

inputs:
  sub_workflows:
    type: list
    description: "List of sub-workflow specifications from complexity analysis"
    required: true

  parent_requirements:
    type: dict
    description: "Original requirements for context"
    required: true

  executor_docs_path:
    type: str
    description: "Path to executor documentation"
    required: true

  examples:
    type: str
    description: "Example workflows for reference"
    required: true

  workspace:
    type: str
    description: "Workspace for generated sub-workflows"
    default: "{{tmp}}/sub-workflows"

  max_depth:
    type: num
    description: "Maximum recursion depth for nested sub-workflows"
    default: 2

  current_depth:
    type: num
    description: "Current recursion depth"
    default: 0

blocks:
  - id: check_depth
    description: "Guard against excessive nesting"
    type: Shell
    inputs:
      command: |
        if [ {{inputs.current_depth}} -ge {{inputs.max_depth}} ]; then
          echo "WARNING: Maximum sub-workflow depth ({{inputs.max_depth}}) reached"
          echo "Skipping further decomposition"
          exit 0
        fi
        echo "Depth {{inputs.current_depth}}/{{inputs.max_depth}} - OK to proceed"

  - id: prepare_sub_requirements
    description: "Create requirements files for each sub-workflow"
    type: CreateFile
    for_each: "{{inputs.sub_workflows}}"
    for_each_mode: parallel
    depends_on: [check_depth]
    condition: "{{inputs.current_depth < inputs.max_depth}}"
    inputs:
      create_parents: true
      overwrite: true
      path: "{{inputs.workspace}}/{{each.value.name}}-requirements.json"
      content: |
        {
          "name": "{{each.value.name}}",
          "description": "{{each.value.purpose}}",
          "inputs": {{each.value.inputs | default([]) | tojson}},
          "outputs": {{each.value.outputs | default([]) | tojson}},
          "steps": ["Generated as sub-workflow of parent requirements"],
          "is_sub_workflow": true,
          "is_recursive": {{each.value.is_recursive | default(false) | tojson}},
          "parent_context": "{{inputs.parent_requirements.name | default('parent')}}"
        }

  - id: generate_sub_workflows
    description: "Recursively call workflow-creator for each sub-workflow (includes design, validation, and save)"
    type: Workflow
    for_each: "{{inputs.sub_workflows}}"
    for_each_mode: sequential
    depends_on: [prepare_sub_requirements]
    condition: "{{inputs.current_depth < inputs.max_depth}}"
    inputs:
      workflow: workflow-creator
      inputs:
        # Pass the sub-workflow requirements as prefilled (skips interactive prompts)
        prefilled_requirements:
          name: "{{each.value.name}}"
          description: "{{each.value.purpose}}"
          inputs: "{{each.value.inputs | default([])}}"
          outputs: "{{each.value.outputs | default([])}}"
          steps: ["Generated as sub-workflow"]
          tags: ["sub-workflow", "{{inputs.parent_requirements.name | default('parent')}}"]
        workspace: "{{inputs.workspace}}/{{each.value.name}}"
        recursion_depth: "{{inputs.current_depth + 1}}"
        max_recursion_depth: "{{inputs.max_depth}}"
        max_validation_attempts: 5

  - id: collect_results
    description: "Summarize generated sub-workflows"
    type: Shell
    depends_on:
      - block: generate_sub_workflows
        required: false
      - block: prepare_sub_requirements
        required: false
    inputs:
      command: |
        echo "Sub-workflow generation summary:"
        echo "  Depth: {{inputs.current_depth}}/{{inputs.max_depth}}"
        echo "  Sub-workflows requested: {{inputs.sub_workflows | length}}"
        echo "  Workspace: {{inputs.workspace}}"
        echo ""
        echo "Generated sub-workflows saved to ~/.workflows/"

outputs:
  sub_workflow_count:
    value: "{{inputs.sub_workflows | length}}"
    type: num
    description: "Number of sub-workflows generated"

  workspace:
    value: "{{inputs.workspace}}"
    type: str
    description: "Path to sub-workflow workspace"

  success:
    value: "{{blocks.collect_results.succeeded}}"
    type: bool
    description: "Whether decomposition completed"
