name: Publish to PyPI

on:
  # Automatically trigger when semantic-release creates and pushes a version tag
  push:
    tags:
      - 'v*'

  # Manual trigger for testing with Test PyPI
  workflow_dispatch:

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version detection

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build distribution packages
        run: uv build

      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    # Only run on automatic tag push
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/workflows-mcp

    permissions:
      id-token: write  # Required for trusted publishing (OIDC)

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true  # Generate digital attestations (default)
          verbose: true

  publish-to-testpypi:
    name: Publish to Test PyPI
    # Only run on manual testing
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/workflows-mcp

    permissions:
      id-token: write  # Required for trusted publishing (OIDC)

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
          verbose: true
